name: aplicaciones_moviles_app
description: "Aplicaciones moviles II"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1 #1
  json_annotation: ^4.0.1 #2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^6.8.0
  build_runner_core: ^7.2.9
  dio: ^4.0.0 #1

flutter:
  uses-material-design: true
  assets:
    - assets/form_data.json